import test, {before, after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium, expect} from '@playwright/test';
import {createApp, localDatabase, serve} from '../scripts/local-server.mjs';
import {passwordHash} from '../server/auth.js';
import {hash} from '../server/domain.js';
const {db, binding} = await localDatabase();
let server;
let browser;
before(async () => {
  await db.doc('settings/app').set({billingEnabled: false, publicRegistration: false});
  for (const name of ['author', 'wife', 'admin']) {
    const uid = `ui-${name}`, email = `ui-${name}@example.test`;
    await db.doc(`accounts/${uid}`).set({id: uid, email, name, verified: true, admin: name === 'admin', password: await passwordHash('browser-test-2026'), sessionVersion: 'browser'});
    await db.doc(`accountEmails/${hash(email)}`).set({uid});
    await db.doc(`users/${uid}`).set({name, email, approved: true, complimentary: false, household_id: '', membership_epoch: uid, created_at: Date.now()});
  }
  server = await serve(createApp({db, secrets: {local: true}}));
  browser = await chromium.launch({headless: true, ...(process.env.REEL_BROWSER_CHANNEL ? {channel: process.env.REEL_BROWSER_CHANNEL} : process.platform === 'darwin' ? {channel: 'chrome'} : {})});
  await mkdir('test-results', {recursive: true});
});
after(async () => { await browser?.close(); await server?.close(); binding.close(); });
async function login(page, who) {
  await page.goto(server.base);
  await page.locator('#auth-form').getByLabel('Email', {exact: true}).fill(`ui-${who}@example.test`);
  await page.getByLabel('Password', {exact: true}).fill('browser-test-2026');
  await page.getByRole('button', {name: 'Open my diary', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'Your life in movies.'})).toBeVisible();
}
test('diary, household, consent sharing, account revocation, and mobile layout work in the browser', {timeout: 120000}, async () => {
  const context = await browser.newContext({viewport: {width: 1440, height: 1000}}), other = await browser.newContext();
  const page = await context.newPage(), wife = await other.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message)); wife.on('pageerror', error => errors.push(error.message));
  await login(page, 'author');
  await page.getByRole('button', {name: '＋ Log a film', exact: true}).click();
  await page.getByLabel('Film title', {exact: true}).fill('The Apartment');
  await page.getByLabel('Release year', {exact: false}).fill('1960');
  await page.getByLabel('Watched with', {exact: true}).last().selectOption('companions');
  await page.getByRole('button', {name: '＋ My wife', exact: true}).click();
  await expect(page.locator('#companion-choices')).toContainText('My wife');
  await page.getByLabel('A little note', {exact: false}).fill('A quiet evening together.');
  await page.getByRole('button', {name: 'Save film ↗', exact: true}).click();
  await expect(page.locator('.movie-card')).toContainText('The Apartment');
  await page.getByRole('button', {name: 'Our household', exact: false}).click();
  await page.getByLabel('Household name').fill('The Friday Film Club');
  await page.getByRole('button', {name: 'Create household ↗', exact: true}).click();
  await page.getByRole('button', {name: 'Create invitation code ↗', exact: true}).click();
  const code = await page.getByLabel('Share this code').inputValue();
  await login(wife, 'wife');
  await wife.getByRole('button', {name: 'Our household', exact: false}).click();
  await wife.getByLabel('Invitation code', {exact: true}).fill(code);
  await wife.getByRole('button', {name: 'Join household ↗', exact: true}).click();
  await expect(wife.getByRole('heading', {name: 'The Friday Film Club'})).toBeVisible();
  await page.getByRole('button', {name: 'Watching companions', exact: false}).click();
  await page.getByLabel('Family account (optional)').selectOption('ui-wife');
  await page.getByLabel('Share all earlier viewings', {exact: false}).check();
  await page.getByRole('button', {name: 'Save companion', exact: true}).click();
  await expect(page.locator('#toast')).toContainText('earlier viewing');
  await wife.getByRole('button', {name: /Film diary/}).click();
  await expect(wife.locator('.movie-card')).toContainText('A quiet evening together.');
  await expect(wife.locator('.movie-card')).toContainText('You watched this');
  await page.getByRole('button', {name: /Film diary/}).click();
  await page.getByRole('button', {name: 'Edit entry ↗'}).click();
  await page.getByLabel('Who can see this?').selectOption('personal');
  await page.getByRole('button', {name: 'Save film ↗'}).click();
  await expect(page.locator('#entry-dialog')).not.toBeVisible();
  await wife.getByRole('button', {name: /Film diary/}).click();
  await expect(wife.locator('.movie-card')).toHaveCount(0);
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({path: 'test-results/diary-desktop.png', fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({path: 'test-results/diary-mobile.png', fullPage: true});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile layout should not overflow horizontally');
  await page.getByRole('button', {name: 'Membership', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'Reel Together membership'})).toBeVisible();
  await page.getByRole('button', {name: /Film diary/}).click();
  await expect(page.locator('.movie-card')).toHaveCount(1);
  assert.deepEqual(errors, []);
  await context.close(); await other.close();
});
test('owner can review invitations and grant account access from administration', {timeout: 60000}, async () => {
  const context = await browser.newContext(), page = await context.newPage();
  await login(page, 'admin');
  await page.getByRole('button', {name: 'Administration', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'Accounts', exact: true})).toBeVisible();
  await page.getByLabel('Approve an email address').fill('future@example.test');
  await page.locator('#approve-email').getByRole('button', {name: 'Approve email', exact: true}).click();
  await expect(page.locator('#admin-message')).toHaveText('Email approved.');
  const form = page.locator('form[data-user-id="ui-wife"]');
  await form.getByLabel('Complimentary membership').check();
  await form.getByRole('button', {name: 'Save account'}).click();
  await expect(page.locator('#admin-message')).toHaveText('Saved.');
  assert.equal((await db.doc('users/ui-wife').get()).data().complimentary, true);
  await context.close();
});
