import test, {before, after} from 'node:test';
import assert from 'node:assert/strict';
import {initializeApp, deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {createApp} from '../functions/src/app.js';
import {Billing} from '../functions/src/billing.js';
import {Catalog} from '../functions/src/catalog.js';
import {StripeFixture} from './stripe-fixture.mjs';

const project = 'demo-reel-together';
if (!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_AUTH_EMULATOR_HOST || process.env.GCLOUD_PROJECT !== project) throw new Error('Integration tests require the isolated demo Firebase emulators.');
const adminApp = initializeApp({projectId: project}), db = getFirestore(), auth = getAuth();
const stripe = new StripeFixture(), secrets = {origin: 'https://films.example.test', kinopoiskToken: 'fixture', stripe: {test: {secretKey: 'sk_test_fixture'}, live: {secretKey: 'sk_live_fixture'}}};
const billing = new Billing(db, secrets, stripe.factory);
const catalog = new Catalog(db, secrets, async url => new Response(JSON.stringify(url.pathname === '/api/v2.2/films/430' ? {kinopoiskId: 430, nameRu: 'Шрек', year: 2001, imdbId: 'tt0126029', ratingKinopoisk: 8, ratingImdb: 7.9, posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/430.jpg'} : {items: [{kinopoiskId: 430, nameRu: 'Шрек', year: 2001, imdbId: 'tt0126029', ratingKinopoisk: 8}]}), {status: 200, headers: {'Content-Type': 'application/json'}}));
let server, base;
const tokens = {};
async function user(key, {admin = false, verified = true, approved = true} = {}) {
  const uid = `test-${key}`, address = `${key}@example.test`;
  await auth.createUser({uid, email: address, password: 'test-password-2026', emailVerified: verified, displayName: key});
  if (admin) await auth.setCustomUserClaims(uid, {admin: true});
  await db.doc(`users/${uid}`).set({name: key, email: address, approved, complimentary: false, household_id: '', membership_epoch: uid, created_at: Date.now()});
  const response = await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({email: address, password: 'test-password-2026', returnSecureToken: true})});
  tokens[key] = (await response.json()).idToken; assert.ok(tokens[key]); return uid;
}
async function call(who, route, method = 'GET', body, headers = {}) {
  const response = await fetch(`${base}/api/${route}`, {method, headers: {'Content-Type': 'application/json', ...(who ? {Authorization: `Bearer ${tokens[who] || who}`} : {}), ...headers}, body: body === undefined ? undefined : JSON.stringify(body)});
  return {status: response.status, data: await response.json(), headers: response.headers};
}
async function ok(who, route, method = 'GET', body, expected = 200) { const result = await call(who, route, method, body); assert.equal(result.status, expected, JSON.stringify(result.data)); return result.data; }
const viewing = (title = 'A private film', more = {}) => ({movie: {title, year: 2001}, status: 'watched', scope: 'personal', watched_on: '2024-01-01', notes: 'Private notes', ...more});
async function hook(uid, mode = 'live', changes = {}, timestamp) {
  const {payload, signature} = stripe.webhook(uid, mode, changes, timestamp);
  const response = await fetch(`${base}/api/billing/webhook/${mode}`, {method: 'POST', headers: {'Content-Type': 'application/json', 'Stripe-Signature': signature}, body: payload});
  return {status: response.status, data: await response.json()};
}
before(async () => {
  await db.doc('settings/app').set({billingEnabled: false, publicRegistration: false});
  server = createApp({db, auth, secrets, catalog, billing}).listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve)); base = `http://127.0.0.1:${server.address().port}`;
  await user('owner', {admin: true}); await user('author'); await user('wife'); await user('third'); await user('outsider'); await user('unverified', {verified: false}); await user('pending', {approved: false});
});
after(async () => { await new Promise(resolve => server.close(resolve)); await db.terminate(); await deleteApp(adminApp); });

test('authentication, approval, and direct Firestore access are enforced', async () => {
  assert.equal((await call(null, 'entries')).status, 401);
  assert.equal((await call('forged-token', 'entries')).status, 401);
  assert.equal((await call('unverified', 'session')).status, 403);
  assert.equal((await ok('pending', 'session')).approved, false);
  assert.equal((await call('pending', 'entries')).status, 403);
  assert.equal((await call('author', 'admin/overview')).status, 403);
  await ok('owner', 'admin/approve-email', 'POST', {email: 'pending@example.test'});
  assert.equal((await ok('pending', 'session')).approved, true);
  const direct = await fetch(`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${project}/databases/(default)/documents/users/test-author`, {headers: {Authorization: `Bearer ${tokens.author}`}});
  assert.equal(direct.status, 403);
  const write = await fetch(`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${project}/databases/(default)/documents/users/test-author`, {method: 'PATCH', headers: {Authorization: `Bearer ${tokens.author}`, 'Content-Type': 'application/json'}, body: JSON.stringify({fields: {complimentary: {booleanValue: true}}})});
  assert.equal(write.status, 403);
});
test('private entries, validation, repeat viewings, and watchlist race protection', async () => {
  const entry = await ok('author', 'entries', 'POST', viewing(), 201);
  assert.equal((await ok('outsider', 'entries')).total, 0);
  assert.equal((await call('outsider', `entries/${entry.id}`, 'PUT', viewing('Stolen'))).status, 403);
  assert.equal((await call('outsider', `entries/${entry.id}`, 'DELETE')).status, 403);
  for (const patch of [{rating: 8}, {watched_on: '2023-02-29'}, {scope: 'household'}, {watch_company: 'companions', companion_ids: ['not-mine']}]) assert.equal((await call('author', 'entries', 'POST', viewing('Invalid', patch))).status, 400);
  await ok('author', 'entries', 'POST', viewing(), 201);
  assert.equal((await ok('author', 'entries?q=A%20private%20film')).total, 2);
  const watchlist = viewing('Next film', {status: 'watchlist'});
  const results = await Promise.all([call('author', 'entries', 'POST', watchlist), call('author', 'entries', 'POST', watchlist)]);
  assert.deepEqual(results.map(r => r.status).sort(), [201, 409]);
  const watchId = results.find(r => r.status === 201).data.id;
  await ok('author', `entries/${watchId}`, 'PUT', viewing('Next film'));
  await ok('author', 'entries', 'POST', watchlist, 201);
  assert.equal((await ok('author', 'entries?status=watchlist')).total, 1);
  assert.equal((await call('author', 'entries?page=-1')).status, 400);
  assert.match((await call('author', 'entries')).headers.get('cache-control'), /no-store/);
});
test('catalog metadata is server verified and manual links never forge ratings', async () => {
  const result = await ok('author', 'lookup?provider=kinopoisk&id=430');
  assert.equal(result.title, 'Шрек');
  await ok('author', 'entries', 'POST', viewing('ignored', {movie: {...result, title: 'Forged title', kinopoisk_rating: 10, poster_url: 'https://evil.example/x.jpg'}}), 201);
  const saved = (await ok('author', 'entries?q=Шрек')).items[0];
  assert.equal(saved.kinopoisk_rating, 8); assert.equal(saved.title, 'Шрек');
  assert.equal((await call('author', 'entries', 'POST', viewing('Unverified catalog', {movie: {title: 'Fake', kinopoisk_id: 9999}}))).status, 400);
  await ok('author', 'entries', 'POST', viewing('Manual linked', {movie: {title: 'Manual linked', links: {kinopoisk: '430', imdb: 'tt0126029'}, kinopoisk_rating: 10}}), 201);
  const manual = (await ok('author', 'entries?q=Manual')).items[0];
  assert.equal(manual.linked_imdb_id, 'tt0126029'); assert.equal(manual.kinopoisk_rating, null);
});
test('companion sharing needs consent, cannot leak to household peers, and revokes on relink or rejoin', async () => {
  await ok('author', 'household', 'POST', {name: 'Our cinema'}, 201);
  let invitation = await ok('author', 'household/invite', 'POST', {});
  await ok('wife', 'household/join', 'POST', invitation); await ok('third', 'household/join', 'POST', invitation);
  assert.equal((await call('wife', 'household/invite', 'POST', {})).status, 403);
  let c = await ok('author', 'companions', 'POST', {name: 'My wife', linked_user_id: 'test-wife'}, 201);
  const body = viewing('Tagged private', {watch_company: 'companions', companion_ids: [c.id]});
  const entry = await ok('author', 'entries', 'POST', body, 201);
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  c = await ok('author', `companions/${c.id}`, 'PUT', {name: 'My wife', linked_user_id: 'test-wife', share_existing: true});
  assert.equal(c.shared_count, 1);
  assert.equal((await ok('wife', 'entries?scope=mine&q=Tagged')).items[0].notes, 'Private notes');
  assert.equal((await ok('third', 'entries?q=Tagged')).total, 0);
  assert.equal((await call('wife', `entries/${entry.id}`, 'PUT', body)).status, 403);
  await ok('author', 'entries', 'POST', {...body, movie: {title: 'New private'}}, 201);
  assert.equal((await ok('wife', 'entries?q=New%20private')).total, 0);
  await ok('author', `entries/${entry.id}`, 'PUT', body);
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  await ok('author', `entries/${entry.id}`, 'PUT', {...body, scope: 'linked', shared_companion_ids: [c.id]});
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 1);
  await ok('author', `companions/${c.id}`, 'PUT', {name: 'My wife', linked_user_id: 'test-third'});
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  assert.equal((await ok('third', 'entries?q=Tagged')).total, 0);
  await ok('author', `companions/${c.id}`, 'PUT', {name: 'My wife', linked_user_id: 'test-wife'});
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  await ok('author', `companions/${c.id}`, 'PUT', {name: 'My wife', linked_user_id: 'test-wife', share_existing: true});
  await ok('wife', 'household/membership', 'DELETE');
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  await ok('wife', 'household/join', 'POST', invitation);
  assert.equal((await ok('wife', 'entries?q=Tagged')).total, 0);
  await ok('author', `companions/${c.id}`, 'PUT', {name: 'My partner', linked_user_id: 'test-wife', share_existing: true});
  await ok('author', 'entries', 'POST', viewing('Household viewing', {scope: 'household', watch_company: 'companions', companion_ids: [c.id]}), 201);
  assert.equal((await ok('wife', 'entries?scope=mine&q=Household')).total, 1);
  assert.equal((await ok('third', 'entries?scope=mine&q=Household')).total, 0);
  assert.equal((await ok('third', 'entries?scope=household&q=Household')).total, 1);
  const privateCompanion = await ok('author', 'companions', 'POST', {name: 'Private label'}, 201);
  assert.ok(!(await ok('third', 'bootstrap')).companions.some(c => c.id === privateCompanion.id));
  await ok('author', 'household/members/test-wife', 'DELETE');
  assert.equal((await ok('wife', 'entries')).total, 0);
  assert.equal((await call('wife', 'household/join', 'POST', invitation)).status, 400);
  assert.equal((await call('author', 'household/membership', 'DELETE')).status, 400);
});
test('invitation requests deduplicate without exposing contact data and require admin moderation', async () => {
  await ok(null, 'invitations', 'POST', {name: 'Guest', email: 'guest@example.test'});
  await ok(null, 'invitations', 'POST', {name: 'Overwrite', email: 'guest@example.test'});
  const list = await ok('owner', 'admin/invitations');
  assert.equal(list.items.length, 1); assert.equal(list.items[0].name, 'Guest');
  assert.equal((await call('author', 'admin/invitations')).status, 403);
  await ok('owner', `admin/invitations/${list.items[0].id}`, 'PUT', {status: 'handled'});
  await ok('owner', `admin/invitations/${list.items[0].id}`, 'DELETE');
  assert.equal((await ok('owner', 'admin/invitations')).items.length, 0);
});
test('billing verifies test proof, isolates live accounts, rejects forged webhooks, and retains diary data', async () => {
  await user('payer'); await user('otherpayer');
  await ok('payer', 'entries', 'POST', viewing('Retained diary'), 201);
  assert.equal((await call('payer', 'billing/checkout', 'POST', {mode: 'test'})).status, 403);
  await ok('owner', 'admin/billing/setup', 'POST', {mode: 'test'}); await ok('owner', 'admin/billing/setup', 'POST', {mode: 'live'});
  assert.equal((await call('owner', 'admin/billing/enable', 'POST', {enabled: true})).status, 400);
  await ok('owner', 'billing/checkout', 'POST', {mode: 'test'});
  const testSession = stripe.complete('test-owner', 'test');
  await ok('owner', 'billing/return', 'POST', {mode: 'test', session_id: testSession.id});
  assert.equal((await call('owner', 'admin/billing/enable', 'POST', {enabled: true})).status, 400);
  assert.equal((await hook('test-owner', 'test')).status, 200);
  await ok('owner', 'admin/billing/enable', 'POST', {enabled: true});
  assert.equal((await call('payer', 'entries')).status, 402);
  await ok('owner', 'entries');
  assert.equal((await call('payer', 'admin/users/test-payer', 'PUT', {complimentary: true})).status, 403);
  await ok('owner', 'admin/users/test-payer', 'PUT', {complimentary: true}); await ok('payer', 'entries');
  assert.equal((await call('payer', 'billing/checkout', 'POST', {})).status, 409);
  await ok('owner', 'admin/users/test-payer', 'PUT', {complimentary: false});
  const first = await ok('payer', 'billing/checkout', 'POST', {user_id: 'test-otherpayer', price: 'price_wrong', quantity: 10, return_url: 'https://evil.example'});
  const second = await ok('payer', 'billing/checkout', 'POST', {}); assert.equal(first.url, second.url);
  const checkouts = stripe.calls.filter(c => c.mode === 'live' && c.type === 'checkout');
  assert.equal(checkouts.length, 1); assert.equal(checkouts[0].body.client_reference_id, 'test-payer'); assert.equal(checkouts[0].body.line_items[0].quantity, 1); assert.equal(checkouts[0].body.line_items[0].price, 'price_live'); assert.ok(checkouts[0].body.success_url.startsWith('https://films.example.test/'));
  const row = (await db.doc('billingAccounts/live_test-payer').get()).data();
  assert.equal((await call('otherpayer', 'billing/return', 'POST', {session_id: row.checkout_id})).status, 403);
  assert.equal((await call('payer', 'billing/return', 'POST', {session_id: row.checkout_id})).status, 403);
  assert.equal((await call(null, 'billing/webhook/live', 'POST', {})).status, 400);
  stripe.complete('test-payer');
  assert.equal((await hook('test-payer', 'live', {}, Math.floor(Date.now() / 1000) - 600)).status, 400);
  assert.equal((await hook('test-payer', 'live', {livemode: false})).status, 400);
  assert.equal((await hook('test-payer')).status, 200);
  assert.equal((await ok('payer', 'entries')).items[0].title, 'Retained diary');
  assert.equal((await call('otherpayer', 'entries')).status, 402);
  assert.equal((await call('payer', 'billing/checkout', 'POST', {})).status, 409);
  await ok('payer', 'billing/portal', 'POST', {customer: 'cus_fake'});
  assert.equal(stripe.calls.filter(c => c.type === 'portal').at(-1).body.customer, row.customer_id);
  const sub = stripe.subscription('test-payer'); sub.cancel_at_period_end = true;
  await hook('test-payer'); assert.equal((await ok('payer', 'membership')).state, 'ending');
  sub.status = 'past_due'; sub.latest_invoice.status = 'open'; await hook('test-payer');
  assert.equal((await call('payer', 'entries')).status, 402); await ok('payer', 'billing/portal', 'POST', {});
  sub.status = 'active'; sub.latest_invoice.status = 'paid'; await hook('test-payer'); await ok('payer', 'entries');
  sub.status = 'canceled'; await hook('test-payer'); await hook('test-payer'); assert.equal((await call('payer', 'entries')).status, 402);
  assert.equal((await ok('payer', 'membership')).can_subscribe, true, 'Canceled members can subscribe again even when they already have a Stripe customer');
  sub.status = 'active'; sub.items.data[0].current_period_end = Math.floor(Date.now() / 1000) - 1; await hook('test-payer'); assert.equal((await call('payer', 'entries')).status, 402);
  stripe.fail = true; assert.equal((await hook('test-payer')).status, 503); stripe.fail = false;
  const summary = JSON.stringify(await ok('owner', 'admin/overview')); assert.ok(!summary.includes('sk_live') && !summary.includes('whsec_'));
  assert.ok(!JSON.stringify(await ok('payer', 'membership')).includes('cus_'));
  await ok('owner', 'admin/billing/enable', 'POST', {enabled: false});
  assert.equal((await ok('payer', 'entries')).total, 1);
});
