import {spawn} from 'node:child_process';
import {readFile, writeFile, mkdir} from 'node:fs/promises';

export async function packageApp() {
  await mkdir('.spacefast', {recursive: true});
  const archive = '.spacefast/build-output.tgz';
  await new Promise((resolve, reject) => {
    const child = spawn(process.execPath, ['node_modules/spacefast/dist/cli.js', 'build', 'dist', '--prebuilt', '--output', archive, '--json', '--no-stream'], {stdio: 'inherit'});
    child.on('error', reject);
    child.on('exit', code => code ? reject(new Error(`Packaging exited ${code}`)) : resolve());
  });
  const path = `${archive}.meta.json`, metadata = JSON.parse(await readFile(path, 'utf8'));
  const declared = JSON.parse(await readFile('sf.jsonc', 'utf8')).runtime;
  const artifact = metadata.sourceMetadata?.spacefastFunctions?.finalize?.artifact;
  if (!artifact || artifact.format !== 'spacefast.functions.worker.v1') throw new Error('The Spacefast package is missing its Functions artifact.');
  // Explicit author declarations in the supported prebuilt artifact contract.
  // CLI 0.4.1's older config analyzer loses runtime.fetch before compilation.
  // Preserve the exact bundle digest, routes and archive generated by sf build.
  artifact.capabilities.db = declared.database === true;
  artifact.capabilities.fetch = declared.fetch === true;
  artifact.compatibilityDate = declared.compatibilityDate ?? artifact.compatibilityDate;
  await writeFile(path, JSON.stringify(metadata, null, 2) + '\n');
  return archive;
}
