import {api, escape} from './api.js';

let generation = 0;
const heading = (title, description) => `<section class="page-heading"><div><p class="eyebrow">YOUR LITTLE CINEMA</p><h1>${title}</h1><p class="intro">${description}</p></div></section>`;
function begin() { window.dispatchEvent(new Event('reel-section')); const screen = document.getElementById('screen'); screen.setAttribute('aria-busy', 'true'); screen.innerHTML = '<p class="loading">Opening…</p>'; document.querySelectorAll('[data-view]').forEach(e => { e.classList.remove('active'); e.removeAttribute('aria-current'); }); return {screen, version: ++generation}; }
function navigate(url) {
  const parsed = new URL(url);
  if (parsed.protocol !== 'https:' || !['checkout.stripe.com', 'billing.stripe.com'].includes(parsed.hostname)) throw new Error('The payment service returned an unexpected destination.');
  location.assign(parsed.href);
}
export async function membership(message = '') {
  const {screen, version} = begin();
  try {
    const status = await api('membership'); if (version !== generation || !screen.isConnected) return;
    const descriptions = {disabled: 'The diary is currently free to use.', administrator: 'Your administrator account has access.', complimentary: 'The owner has given you complimentary access.', active: 'Your membership is active. Enjoy your next movie night.', ending: 'Your membership will end after the current paid period.', past_due: 'Your renewal payment did not complete. Update your payment method to reopen the diary.', inactive: 'Subscribe for €1 per month to open your diary. Your saved entries stay here when membership ends.'};
    screen.innerHTML = `${heading('A seat for <em>you.</em>', 'One personal membership. A lifetime of movie memories.')}<section class="household-card"><p class="eyebrow">€1 PER PERSON / MONTH</p><h2>Reel Together membership</h2><p>${descriptions[status.state] || descriptions.inactive}</p>${status.paid_until && ['active', 'ending'].includes(status.state) ? `<p>Paid through ${new Date(status.paid_until * 1000).toLocaleDateString()}.</p>` : ''}<div class="membership-actions">${status.can_subscribe ? '<button class="button primary" data-billing="checkout">Subscribe for €1/month</button>' : ''}${status.can_manage ? '<button class="button secondary" data-billing="portal">Manage billing</button>' : ''}<button class="button secondary" id="refresh-membership">Refresh status</button></div><p id="membership-message" class="form-error" role="status">${escape(message)}</p><p class="helper">Cancel through Manage billing. Access remains until the paid period ends. Complimentary access and turning off paid access do not cancel an existing subscription.</p></section>`;
    screen.querySelectorAll('[data-billing]').forEach(button => button.onclick = async () => {
      button.disabled = true;
      try { navigate((await api(`billing/${button.dataset.billing}`, 'POST', {})).url); }
      catch (error) { document.getElementById('membership-message').textContent = error.message; button.disabled = false; }
    });
    document.getElementById('refresh-membership').onclick = () => membership();
  } catch (error) { if (screen.isConnected && generation === version) screen.innerHTML = `${heading('Membership', '')}<p role="alert">${escape(error.message)}</p><button class="button secondary" id="retry-membership">Try again</button>`; screen.querySelector('#retry-membership')?.addEventListener('click', () => membership()); }
  finally { screen.setAttribute('aria-busy', 'false'); }
}
export async function administration(message = '', userAfter = '', invitationAfter = '') {
  const {screen, version} = begin();
  try {
    const [overview, users, invitations] = await Promise.all([api('admin/overview'), api(`admin/users?after=${encodeURIComponent(userAfter)}`), api(`admin/invitations?after=${encodeURIComponent(invitationAfter)}`)]);
    if (version !== generation || !screen.isConnected) return;
    screen.innerHTML = `${heading('Keep the <em>seats ready.</em>', 'Manage accounts, invitation requests, and membership.')}<p id="admin-message" class="form-error" role="status">${escape(message)}</p>
      <section class="household-card"><h2>Accounts</h2><form id="registration-form"><label class="share-consent"><input name="public_registration" type="checkbox" ${overview.settings.public_registration ? 'checked' : ''}><span>Allow verified new accounts without owner approval</span></label><button class="button secondary" type="submit">Save registration setting</button></form><form id="approve-email"><label for="approval-email">Approve an email address</label><div class="search-row"><input id="approval-email" name="email" type="email" required maxlength="254" placeholder="family@example.com"><button class="button primary" type="submit">Approve email</button></div><p class="helper">This approves access for an existing or future verified account. It does not create an account or send an email.</p></form><div class="admin-list">${users.items.map(user => `<form class="user-settings" data-user-id="${user.id}"><h3>${escape(user.name)}</h3><p>${escape(user.email)}</p><label class="share-consent"><input name="approved" type="checkbox" ${user.approved ? 'checked' : ''}><span>Approved to use the app</span></label><label class="share-consent"><input name="complimentary" type="checkbox" ${user.complimentary ? 'checked' : ''}><span>Complimentary membership</span></label><button class="button secondary" type="submit">Save account</button></form>`).join('')}</div><div class="pagination">${userAfter ? '<button class="button secondary" id="first-users">First page</button>' : ''}${users.next ? `<button class="button secondary" id="next-users" data-after="${users.next}">Next accounts</button>` : ''}</div></section>
      <section class="household-card"><h2>Invitation requests</h2><p>Arrange accounts personally, then mark requests handled. Declining a request does not revoke an existing account.</p><div class="admin-list">${invitations.items.length ? invitations.items.map(invite => `<article><h3>${escape(invite.name)}</h3><p>${escape(invite.email)} · ${escape(invite.status)}</p><div class="admin-actions"><button class="button secondary" data-approve-address="${escape(invite.email)}">Approve email</button><button class="text-button" data-invitation="${invite.id}" data-status="handled">Mark handled</button><button class="text-button" data-invitation="${invite.id}" data-status="declined">Decline</button><button class="text-button danger" data-delete-invitation="${invite.id}">Delete request</button></div></article>`).join('') : '<p>No requests on this page.</p>'}</div><div class="pagination">${invitationAfter ? '<button class="button secondary" id="first-invitations">First page</button>' : ''}${invitations.next ? `<button class="button secondary" id="next-invitations" data-after="${invitations.next}">Next requests</button>` : ''}</div></section>
      <section class="household-card"><h2>Movie catalogs</h2><p>${overview.catalog_providers.length ? `Connected: ${overview.catalog_providers.map(p => escape(p.name)).join(', ')}.` : 'No catalogs connected. Manual movie titles and links still work.'}</p><p class="helper">The site operator manages catalog connections in the server configuration.</p></section>
      <section class="household-card"><h2>€1/month membership</h2><p>Paid access is <strong>${overview.settings.billing_enabled ? 'open' : 'off'}</strong>.</p><div class="household-grid">${['test', 'live'].map(mode => { const b = overview.billing[mode]; return `<div><h3>${mode === 'test' ? 'Test payments' : 'Live payments'}</h3><p>${b.ready ? 'Connected and prepared.' : b.key_configured ? 'Connection available. Prepare checkout to continue.' : 'Connection not configured by the site operator.'}</p>${mode === 'test' ? `<p>Checkout verified: ${b.checkout_verified ? 'yes' : 'no'}. Webhook verified: ${b.webhook_verified ? 'yes' : 'no'}.</p>` : ''}<div class="admin-actions">${b.key_configured ? `<button class="button secondary" data-setup-mode="${mode}">Connect and prepare ${mode}</button>` : ''}${mode === 'test' && b.ready ? '<button class="button secondary" id="test-checkout">Run test checkout</button><button class="text-button" id="test-portal">Manage test subscription</button>' : ''}</div></div>`; }).join('')}</div><button class="button primary" id="toggle-billing" data-enabled="${!overview.settings.billing_enabled}">${overview.settings.billing_enabled ? 'Turn off paid access' : 'Open €1/month subscriptions'}</button><p class="helper">Opening subscriptions requires verified test checkout and webhook delivery, plus a live Stripe account enabled for charges. Turning paid access off does not cancel subscriptions.</p></section>`;
    const action = async (button, fn, success = 'Saved.') => { button.disabled = true; try { await fn(); await administration(success, userAfter, invitationAfter); } catch (error) { const target = document.getElementById('admin-message'); if (target) target.textContent = error.message; button.disabled = false; } };
    screen.querySelector('#registration-form').onsubmit = event => { event.preventDefault(); action(event.target.querySelector('button'), () => api('admin/settings', 'PUT', {public_registration: event.target.elements.public_registration.checked})); };
    screen.querySelector('#approve-email').onsubmit = event => { event.preventDefault(); action(event.target.querySelector('button'), () => api('admin/approve-email', 'POST', {email: event.target.elements.email.value}), 'Email approved.'); };
    screen.querySelectorAll('.user-settings').forEach(form => form.onsubmit = event => { event.preventDefault(); action(form.querySelector('button'), () => api(`admin/users/${form.dataset.userId}`, 'PUT', {approved: form.elements.approved.checked, complimentary: form.elements.complimentary.checked})); });
    screen.querySelectorAll('[data-approve-address]').forEach(button => button.onclick = () => action(button, () => api('admin/approve-email', 'POST', {email: button.dataset.approveAddress}), 'Email approved.'));
    screen.querySelectorAll('[data-invitation]').forEach(button => button.onclick = () => action(button, () => api(`admin/invitations/${button.dataset.invitation}`, 'PUT', {status: button.dataset.status})));
    screen.querySelectorAll('[data-delete-invitation]').forEach(button => button.onclick = () => { if (confirm('Delete this invitation request and its contact details?')) action(button, () => api(`admin/invitations/${button.dataset.deleteInvitation}`, 'DELETE')); });
    screen.querySelectorAll('[data-setup-mode]').forEach(button => button.onclick = () => action(button, () => api('admin/billing/setup', 'POST', {mode: button.dataset.setupMode}), 'Stripe connection prepared.'));
    screen.querySelector('#test-checkout')?.addEventListener('click', event => action(event.target, async () => navigate((await api('billing/checkout', 'POST', {mode: 'test'})).url)));
    screen.querySelector('#test-portal')?.addEventListener('click', event => action(event.target, async () => navigate((await api('billing/portal', 'POST', {mode: 'test'})).url)));
    screen.querySelector('#toggle-billing').onclick = event => action(event.target, () => api('admin/billing/enable', 'POST', {enabled: event.target.dataset.enabled === 'true'}));
    screen.querySelector('#first-users')?.addEventListener('click', () => administration('', '', invitationAfter));
    screen.querySelector('#next-users')?.addEventListener('click', event => administration('', event.target.dataset.after, invitationAfter));
    screen.querySelector('#first-invitations')?.addEventListener('click', () => administration('', userAfter, ''));
    screen.querySelector('#next-invitations')?.addEventListener('click', event => administration('', userAfter, event.target.dataset.after));
  } catch (error) { if (version === generation && screen.isConnected) screen.innerHTML = `<p role="alert">${escape(error.message)}</p><button id="retry-admin" class="button secondary">Try again</button>`; screen.querySelector('#retry-admin')?.addEventListener('click', () => administration()); }
  finally { screen.setAttribute('aria-busy', 'false'); }
}
window.addEventListener('reel-diary', () => { ++generation; });
